### ISSUE TITLE
NekoSDK

### ISSUE THREAD

**Issue by Cosetto** [ssynn/game_translation#4]
Can you add repack for nekosdk? I know it can read without repacking but adding it would be nice

**Comment by ssynn** [comment]
Sorry, I have no time to do this, may be you can try 'Engima Virtual Box' to repack game files as an exe.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月16日(星期六) 晚上10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [ssynn/game_translation] NekoSDK (#4)





 
Can you add repack for nekosdk? I know it can read without repacking but adding it would be nice
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cosetto** [comment]
oh well, that's too bad

**Comment by ssynn** [comment]
you can create **jp_chs.json** by function **create_dict**, make sure that **jp_all.txt** in directory **intermediate_file**

**Comment by ssynn** [comment]
create_dict(lambda x:x[:-1])

**Comment by Cosetto** [comment]
sorry for bothering you again but is the output_srp function means to import script from jp_all.txt or jp_chs.json back to srp files because every time I import it back those srp files are empty 
![image](https://user-images.githubusercontent.com/81801486/137650536-32a13f14-2ece-46d6-a25b-be8bdfb77f68.png)
![image](https://user-images.githubusercontent.com/81801486/137650641-730ca318-e482-447a-bc78-ca7b2304785c.png)

**Comment by Cosetto** [comment]
Do you have any idea how to line break or word-wrap Yu-ris engine? \r \n /n doesn't work, the only way I know is to use space 
![image](https://user-images.githubusercontent.com/81801486/140258032-79a2d56b-a5d1-4a81-9a71-90d30b9264a9.png)

**Comment by ssynn** [comment]
sorry, I have no idea
but you can squeeze the text to the next line with full-width spaces

**Comment by Cosetto** [comment]
Is the split_line function for word wrapping. If yes then how do I use? I want to test on Anim engine
